CUDA_VISIBLE_DEVICES=0,1 python main.py \
  --test_data_dir ../scene_text_benchmarks/IIIT5K_3000 \
  --batch_size 256 \
  --workers 4 \
  --height 32 \
  --width 100 \
  --arch ResNet45 \
  --decode_type Attention \
  --with_lstm \
  --max_len 25 \
  --STN_ON \
  --tps_inputsize 32 64 \
  --tps_outputsize 32 100 \
  --tps_margins 0.05 0.05 \
  --stn_activation none \
  --num_control_points 20 \
  --alphabets lowercase \
  --lower \
  --iter_mode \
  --evaluate \
  --resume weights/ASTER/model_best_acc_bias.pth.tar \